# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9e971e51be26dde6997645812f80bdb956f48d53fd0b497845cb23853d02014e42ae35a50e9f92930a28b03c03fce2c42ffddc6abed1cb46062a38c2ca13c7f5
  twitter_api_key: 8r95MxMH0ktnIsmHDDicyhbO9
  twitter_api_secret: autP2eOAeYXR6LvabBQIwM9xDZ3392zjlBz44uE7sxVAoMq3ZI

test:
  secret_key_base: 1d99495bacf5f3dca795e8ee71130929a82c843a9c172d8c4cfc5c4793580871635a424476d5d2ab1a34b9cc3eb437904cf172036d91269521fdb18d9902f517

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
